android.useAndroidX=true
android.nonTransitiveRClass=true
kotlin.code.style=official
# Speicher: 7 GB Maschine, deshalb bewusst begrenzt.
org.gradle.jvmargs=-Xmx2048m -XX:MaxMetaspaceSize=512m -Djava.net.preferIPv4Stack=true
kotlin.daemon.jvmargs=-Xmx1024m
org.gradle.workers.max=2
org.gradle.caching=true
